set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMakeTargets")

set(ENGINE_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(ENGINE_EXT_DIR ${ENGINE_ROOT_DIR}/ext)
set(ENGINE_LIB_DIR ${ENGINE_ROOT_DIR}/lib)